### ISSUE TITLE
Flash pinecil from a phone

### ISSUE THREAD

**Issue by River-Mochi** [Spagett1/PineFlash#20]
Since Egui is used to make web apps.  would it be possible to make pineFlash work on a phone to update Pinecil?
people with android phones often have a USB-C connector. 

gamie said that blisp is possible to run on a phone theoretically for updates.
a long time ago someone  figured out how to update V1  on a phone using dfu-util.  don't know what phone they used and they didn't give details of steps.

**Comment by Spagett1** [comment]
This isn't really possible, at least not for me. Web apps have a lot of restrictions and i don't believe they can call random operating system functions, especially not on android.

The only way i could see this working is if i figured a way to create a native android app from egui (which i think i saw someone do but i don't think the patches are in mainline) and then somehow integrating blisp and dfu-util into it as oppressed to how they are currently called. I also have absolutely no experience coding for android, packaging as an apk or working around their permissions system.

I'm going to mark this as a wontfix because it isn't in the scope of the project for the foreseeable future.
